import Link from "next/link";
import { notFound } from "next/navigation";
import { Shell } from "@/components/dashboard/shell";
import { InvoiceAssignButton } from "@/components/dashboard/invoice-assign-button";
import { InvoiceForm } from "@/components/dashboard/invoice-form";
import { InvoiceStatus } from "@/components/dashboard/invoice-status";
import { ProjectActions } from "@/components/dashboard/project-actions";
import { ProjectStatus } from "@/components/dashboard/project-status";
import { createClient } from "@/lib/supabase/server";

type Invoice = { id: string; invoice_number: string; amount: number; status: string; due_date: string | null };
type Document = { id: string; name: string; storage_path: string; mime_type: string | null; created_at: string };
type Project = { id: string; customer_id: string | null; name: string; location: string | null; project_type: string | null; project_details: Record<string, string>; status: string; customer: { name: string }[] };
const detailLabels: [string, string][] = [["propertyId", "Kiinteistötunnus"], ["permitNumber", "Lupa-/hankenro"], ["startDate", "Aloituspäivä"], ["targetDate", "Tavoitevalmistuminen"], ["siteContact", "Työmaan yhteyshenkilö"], ["sitePhone", "Työmaan puhelin"], ["responsibleForeman", "Vastaava työnjohtaja"], ["kvvSupervisor", "KVV-työnjohtaja"], ["ivSupervisor", "IV-työnjohtaja"], ["principalDesigner", "Pääsuunnittelija"], ["lviDesigner", "LVI-suunnittelija"], ["structuralDesigner", "Rakennesuunnittelija"], ["electricalDesigner", "Sähkösuunnittelija"]];

export default async function ProjectPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const supabase = await createClient();
  const primaryProject = await supabase.from("projects").select("id,customer_id,name,location,project_type,project_details,status,customer:customers(name)").eq("id", id).is("archived_at", null).maybeSingle();
  let project = primaryProject.data as Project | null;
  const detailsMissing = Boolean(primaryProject.error);
  if (detailsMissing) {
    const fallbackProject = await supabase.from("projects").select("id,customer_id,name,location,project_type,status,customer:customers(name)").eq("id", id).is("archived_at", null).maybeSingle();
    project = fallbackProject.data ? { ...fallbackProject.data, project_details: {} } as Project : null;
  }
  const [{ data: invoices }, { data: unassigned }, { data: customers }, { data: documents }] = await Promise.all([
    supabase.from("invoices").select("id,invoice_number,amount,status,due_date").eq("project_id", id).order("created_at", { ascending: false }),
    supabase.from("invoices").select("id,invoice_number,amount").is("project_id", null).order("created_at", { ascending: false }),
    supabase.from("customers").select("id,name").is("archived_at", null).order("name"),
    supabase.from("documents").select("id,name,storage_path,mime_type,created_at").eq("project_id", id).order("created_at", { ascending: false }),
  ]);
  if (!project) notFound(); const target = project as Project; const details = target.project_details ?? {}; const rows = (invoices ?? []) as Invoice[]; const docs = (documents ?? []) as Document[]; const loose = (unassigned ?? []) as Pick<Invoice, "id" | "invoice_number" | "amount">[]; const open = rows.filter(invoice => ["draft", "sent", "overdue"].includes(invoice.status)).reduce((sum, invoice) => sum + Number(invoice.amount), 0); const paid = rows.filter(invoice => invoice.status === "paid").reduce((sum, invoice) => sum + Number(invoice.amount), 0);
  return <Shell><Link href="/tyomaat" className="text-sm font-medium text-[#52657c] underline">← Kaikki kohteet</Link><div className="mt-5 flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-[#a67a00]">Kohteen seuranta</p><h1 className="mt-2 text-3xl font-semibold">{target.name}</h1><p className="mt-2 text-sm text-[#607188]">{target.customer[0]?.name ?? "Tilaaja puuttuu"}{target.location ? ` · ${target.location}` : ""}{target.project_type ? ` · ${target.project_type}` : ""}</p></div><div className="flex flex-col items-end gap-3"><ProjectStatus id={target.id} status={target.status} /><ProjectActions project={{ id: target.id, name: target.name, location: target.location, projectType: target.project_type, customerId: target.customer_id, details }} customers={customers ?? []} /></div></div>
    <section className="mt-8 grid gap-4 sm:grid-cols-3"><div className="border border-[#d6dee7] border-t-4 border-t-[#d9ae16] bg-white p-5"><p className="text-xs font-semibold uppercase text-[#607188]">Avoinna</p><p className="mt-2 text-3xl font-semibold">{open.toLocaleString("fi-FI", { style: "currency", currency: "EUR" })}</p></div><div className="border border-[#d6dee7] border-t-4 border-t-[#2c6e49] bg-white p-5"><p className="text-xs font-semibold uppercase text-[#607188]">Maksettu</p><p className="mt-2 text-3xl font-semibold">{paid.toLocaleString("fi-FI", { style: "currency", currency: "EUR" })}</p></div><div className="border border-[#d6dee7] border-t-4 border-t-[#112b49] bg-white p-5"><p className="text-xs font-semibold uppercase text-[#607188]">Tallennetut laskut</p><p className="mt-2 text-3xl font-semibold">{rows.length}</p></div></section>
    <section className="mt-8 border border-[#d6dee7] bg-white p-5"><h2 className="text-xl font-semibold">Työmaan tiedot</h2><div className="mt-4 grid gap-x-8 gap-y-3 sm:grid-cols-2">{detailLabels.filter(([key]) => details[key]).map(([key, label]) => <p key={key} className="text-sm"><span className="block text-xs font-semibold uppercase text-[#607188]">{label}</span>{details[key]}</p>)}</div>{details.notes && <p className="mt-4 border-t pt-4 text-sm"><span className="block text-xs font-semibold uppercase text-[#607188]">Lisätiedot</span>{details.notes}</p>}{!detailLabels.some(([key]) => details[key]) && !details.notes && <p className="mt-3 text-sm text-[#607188]">Täydennä vastuuhenkilöt, suunnittelijat ja muut työmaatiedot Muokkaa tietoja -toiminnolla.</p>}</section>
    {loose.length > 0 && <section className="mt-8 border border-red-300 bg-red-50 p-5"><h2 className="font-semibold text-red-900">Kohdistamattomat myyntilaskut</h2><p className="mt-1 text-sm text-red-800">Voit kohdistaa laskun suoraan tähän työmaahan.</p><div className="mt-4 space-y-3">{loose.map(invoice => <div key={invoice.id} className="flex flex-wrap items-center justify-between gap-3 border border-red-200 bg-white p-3 text-sm"><span><b>{invoice.invoice_number}</b> · {Number(invoice.amount).toLocaleString("fi-FI", { style: "currency", currency: "EUR" })}</span><InvoiceAssignButton invoiceId={invoice.id} projectId={target.id} /></div>)}</div></section>}
    <div className="mt-8 flex flex-wrap items-center justify-between gap-4"><div><h2 className="text-xl font-semibold">Myyntilaskut</h2><p className="mt-1 text-sm text-[#607188]">Kirjanpitäjän laskujen seuranta tässä kohteessa.</p></div><InvoiceForm projects={[{ id: target.id, name: target.name }]} defaultProjectId={target.id} /></div><div className="mt-4 overflow-hidden border border-[#d6dee7] bg-white"><div className="grid grid-cols-[1fr_.8fr_.8fr_auto] gap-4 border-b bg-[#f4f7fa] px-5 py-3 text-xs font-semibold uppercase text-[#607188]"><span>Laskunumero</span><span>Eräpäivä</span><span>Summa</span><span>Tila</span></div>{rows.length ? rows.map(invoice => <div key={invoice.id} className="grid grid-cols-[1fr_.8fr_.8fr_auto] gap-4 border-b border-[#e4e9ef] px-5 py-4 text-sm"><b>{invoice.invoice_number}</b><span>{invoice.due_date ?? "—"}</span><span>{Number(invoice.amount).toLocaleString("fi-FI", { style: "currency", currency: "EUR" })}</span><InvoiceStatus id={invoice.id} status={invoice.status} /></div>) : <p className="p-6 text-sm text-[#607188]">Tälle kohteelle ei ole vielä tallennettu laskuja.</p>}</div>
    <section className="mt-8 border border-[#d6dee7] bg-white p-5"><h2 className="text-xl font-semibold">Katselmukset ja dokumentit</h2><p className="mt-1 text-sm text-[#607188]">Tähän kohteeseen kohdistetut kenttämuistiot ja muut dokumentit.</p>{docs.length ? <div className="mt-4 divide-y border border-[#e4e9ef]">{docs.map(document => <div key={document.id} className="flex items-center justify-between gap-4 px-4 py-3 text-sm"><div><b>{document.name}</b><p className="mt-1 text-xs text-[#607188]">{document.mime_type?.includes("valvontamuistio") ? "Valvontamuistio · katselmuspöytäkirja" : document.mime_type || "Dokumentti"}</p></div><span className="text-xs text-[#607188]">{new Date(document.created_at).toLocaleString("fi-FI")}</span></div>)}</div> : <p className="mt-4 text-sm text-[#607188]">Ei vielä kohdistettuja katselmuksia tai dokumentteja.</p>}</section>
    {docs.some(document => document.storage_path.startsWith("valvontamuistio:")) && <section className="mt-4 flex flex-wrap items-center gap-3 border border-[#d6dee7] bg-[#f8fafc] p-4"><p className="mr-2 text-sm text-[#52657c]">Avaa kohteeseen kohdistettu katselmuspöytäkirja PDF-esikatselua ja sähköpostijakoa varten:</p>{docs.filter(document => document.storage_path.startsWith("valvontamuistio:")).map(document => <a key={`open-${document.id}`} href={`https://lvi-valvontamuistio-app.netlify.app/?cloudProject=${encodeURIComponent(document.storage_path.slice("valvontamuistio:".length))}`} target="_blank" rel="noreferrer" className="rounded border border-[#112b49] bg-white px-3 py-2 text-sm font-semibold text-[#112b49] hover:bg-[#112b49] hover:text-white">Avaa {document.name} ↗</a>)}</section>}
  </Shell>;
}
