"use client";
import { useRouter } from "next/navigation";
import { useState } from "react";

const types = ["Yksityishenkilö", "Asunto-osakeyhtiö", "Yritys", "Kunta tai julkinen toimija", "Muu"];
export function CreateCustomer() {
  const router = useRouter(); const [open, setOpen] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  async function save(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setError(""); const form = new FormData(event.currentTarget); const response = await fetch("/api/customers", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: form.get("name"), customerType: form.get("customerType"), contactName: form.get("contactName"), email: form.get("email"), phone: form.get("phone") }) }); const data = await response.json(); if (!response.ok) setError(data.error || "Asiakkaan luonti epäonnistui."); else { setOpen(false); router.refresh(); } setSaving(false); }
  return <><button onClick={() => setOpen(true)} className="rounded bg-[#d9ae16] px-4 py-2.5 text-sm font-semibold text-[#142b45]">+ Uusi asiakas</button>{open && <div className="fixed inset-0 z-50 grid place-items-center bg-[#142b45]/55 p-4"><form onSubmit={save} className="w-full max-w-md bg-white p-6 shadow-2xl"><p className="text-xs font-semibold uppercase tracking-[.14em] text-[#a67a00]">Asiakasrekisteri</p><h2 className="mt-1 text-xl font-semibold">Perusta asiakas</h2><p className="mt-2 text-sm text-[#607188]">Asiakas voi olla yksityishenkilö, As Oy, yritys, kunta tai muu tilaaja. Kohde lisätään asiakkaan alle myöhemmin.</p><label className="mt-5 block text-sm font-medium">Asiakastyyppi<select name="customerType" className="mt-2 w-full border p-3">{types.map(type => <option key={type}>{type}</option>)}</select></label><label className="mt-3 block text-sm font-medium">Nimi<input required name="name" placeholder="Esim. As Oy Mäntyrinne" className="mt-2 w-full border p-3" /></label><label className="mt-3 block text-sm font-medium">Yhteyshenkilö<input name="contactName" className="mt-2 w-full border p-3" /></label><label className="mt-3 block text-sm font-medium">Sähköposti<input name="email" type="email" className="mt-2 w-full border p-3" /></label><label className="mt-3 block text-sm font-medium">Puhelin<input name="phone" className="mt-2 w-full border p-3" /></label>{error && <p className="mt-3 text-sm text-red-700">{error}</p>}<div className="mt-5 flex gap-3"><button disabled={saving} className="rounded bg-[#d9ae16] px-4 py-2 font-semibold">{saving ? "Tallennetaan…" : "Tallenna asiakas"}</button><button type="button" onClick={() => setOpen(false)} className="underline">Peruuta</button></div></form></div>}</>;
}
