"use client";
import { useRouter } from "next/navigation";
import { useState } from "react";

export function CreateUnifiedRecord() {
  const router = useRouter(); const [open, setOpen] = useState(false); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  async function save(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setError(""); const form = new FormData(event.currentTarget); const response = await fetch("/api/workspaces", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: form.get("name"), location: form.get("location"), projectType: form.get("projectType") }) }); const data = await response.json(); if (!response.ok) { setError(data.error || "Kohteen tallennus epäonnistui."); setSaving(false); return; } setOpen(false); router.refresh(); }
  return <><button onClick={() => setOpen(true)} className="rounded bg-[#d9ae16] px-4 py-2.5 text-sm font-semibold text-[#142b45]">+ Uusi kohde</button>{open && <div className="fixed inset-0 z-50 grid place-items-center bg-[#142b45]/55 p-4"><form onSubmit={save} className="w-full max-w-md bg-white p-6 shadow-2xl"><p className="text-xs font-semibold uppercase tracking-[.14em] text-[#a67a00]">Kohderekisteri</p><h2 className="mt-1 text-xl font-semibold">Perusta kohde</h2><p className="mt-2 text-sm text-[#607188]">Tämä yksi tietue toimii asiakkaana, kohteena sekä laskutuksen ja valvonnan seurantapaikkana.</p><label className="mt-5 block text-sm font-medium">Asiakkaan / kohteen nimi<input required name="name" placeholder="Esim. As Oy Hyvinkään Helmi" className="mt-2 w-full border p-3" /></label><label className="mt-3 block text-sm font-medium">Osoite / paikkakunta<input name="location" className="mt-2 w-full border p-3" /></label><label className="mt-3 block text-sm font-medium">Kohdeluokka<input name="projectType" placeholder="Esim. Pientaloyhtiö" className="mt-2 w-full border p-3" /></label>{error && <p className="mt-3 text-sm text-red-700">{error}</p>}<div className="mt-5 flex gap-3"><button disabled={saving} className="rounded bg-[#d9ae16] px-4 py-2 font-semibold">{saving ? "Tallennetaan…" : "Tallenna kohde"}</button><button type="button" onClick={() => setOpen(false)} className="underline">Peruuta</button></div></form></div>}</>;
}
