"use client";
import { useRouter } from "next/navigation";
import { useState } from "react";

type Project = { id: string; name: string; location: string | null; projectType: string | null; details?: Record<string, string> };
const fields: [string, string, string][] = [["propertyId", "Kiinteistötunnus", "text"], ["permitNumber", "Lupa-/hankenro", "text"], ["startDate", "Aloituspäivä", "date"], ["targetDate", "Tavoitevalmistuminen", "date"], ["siteContact", "Työmaan yhteyshenkilö", "text"], ["sitePhone", "Työmaan puhelin", "tel"], ["responsibleForeman", "Vastaava työnjohtaja", "text"], ["kvvSupervisor", "KVV-työnjohtaja", "text"], ["ivSupervisor", "IV-työnjohtaja", "text"], ["principalDesigner", "Pääsuunnittelija", "text"], ["lviDesigner", "LVI-suunnittelija", "text"], ["structuralDesigner", "Rakennesuunnittelija", "text"], ["electricalDesigner", "Sähkösuunnittelija", "text"]];

export function ProjectRowActions({ project }: { project: Project }) {
  const router = useRouter(); const [open, setOpen] = useState(false); const [error, setError] = useState("");
  async function request(method: "PATCH" | "DELETE", body?: object) { setError(""); const response = await fetch(`/api/projects/${project.id}`, { method, headers: { "Content-Type": "application/json" }, body: body ? JSON.stringify(body) : undefined }); const data = await response.json(); if (!response.ok) setError(data.error || "Toiminto epäonnistui."); else { setOpen(false); router.refresh(); } }
  return <div className="flex flex-wrap items-center justify-end gap-3"><button onClick={() => setOpen(true)} className="text-xs font-semibold text-[#142b45] underline">Muokkaa</button><button onClick={() => request("PATCH", { archived: true })} className="text-xs font-semibold text-[#52657c] underline">Arkistoi</button><button onClick={() => { if (confirm(`Poistetaanko kohde “${project.name}” pysyvästi?`)) request("DELETE"); }} className="text-xs font-semibold text-red-700 underline">Poista</button>{error && <p className="basis-full text-right text-xs text-red-700">{error}</p>}{open && <div className="fixed inset-0 z-50 overflow-y-auto bg-[#142b45]/55 p-4"><form onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); const projectDetails = Object.fromEntries([...fields.map(([key]) => key), "notes"].map(key => [key, String(form.get(key) || "")])); request("PATCH", { name: form.get("name"), location: form.get("location"), projectType: form.get("projectType"), projectDetails }); }} className="mx-auto my-6 w-full max-w-3xl bg-white p-6 text-left shadow-2xl"><p className="text-xs font-semibold uppercase tracking-[.14em] text-[#a67a00]">Kohdetiedot</p><h2 className="mt-1 text-xl font-semibold">Muokkaa kohdetta</h2><p className="mt-1 text-sm text-[#607188]">Kaikki kohde-, vastuuhenkilö- ja suunnittelijatiedot tallennetaan tähän yhteen kohteeseen.</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="block text-sm font-medium">Asiakkaan / kohteen nimi<input required name="name" defaultValue={project.name} className="mt-2 w-full border p-3" /></label><label className="block text-sm font-medium">Osoite tai paikkakunta<input name="location" defaultValue={project.location ?? ""} className="mt-2 w-full border p-3" /></label><label className="block text-sm font-medium">Kohdeluokka<input name="projectType" defaultValue={project.projectType ?? ""} className="mt-2 w-full border p-3" /></label>{fields.map(([key, label, type]) => <label key={key} className="block text-sm font-medium">{label}<input name={key} type={type} defaultValue={project.details?.[key] ?? ""} className="mt-2 w-full border p-3" /></label>)}</div><label className="mt-4 block text-sm font-medium">Lisätiedot ja muistiinpanot<textarea name="notes" defaultValue={project.details?.notes ?? ""} rows={4} className="mt-2 w-full border p-3" /></label><div className="mt-5 flex gap-3"><button className="rounded bg-[#d9ae16] px-4 py-2 font-semibold">Tallenna kaikki tiedot</button><button type="button" onClick={() => setOpen(false)} className="underline">Peruuta</button></div></form></div>}</div>;
}
