"use client";
import { useRouter } from "next/navigation";
import { useState } from "react";

type Details = Record<string, string>;
type Project = { id: string; name: string; location: string | null; projectType: string | null; customerId: string | null; details: Details };
type Customer = { id: string; name: string };
const fields: [string, string, string][] = [["propertyId", "Kiinteistötunnus", "text"], ["permitNumber", "Lupa-/hankenro", "text"], ["startDate", "Aloituspäivä", "date"], ["targetDate", "Tavoitevalmistuminen", "date"], ["nextInspectionDate", "Seuraava katselmus", "date"], ["nextInspectionNote", "Katselmuksen aihe", "text"], ["siteContact", "Työmaan yhteyshenkilö", "text"], ["sitePhone", "Työmaan puhelin", "tel"], ["responsibleForeman", "Vastaava työnjohtaja", "text"], ["kvvSupervisor", "KVV-työnjohtaja", "text"], ["ivSupervisor", "IV-työnjohtaja", "text"], ["principalDesigner", "Pääsuunnittelija", "text"], ["lviDesigner", "LVI-suunnittelija", "text"], ["structuralDesigner", "Rakennesuunnittelija", "text"], ["electricalDesigner", "Sähkösuunnittelija", "text"]];

export function ProjectActions({ project, customers }: { project: Project; customers: Customer[] }) {
  const router = useRouter(); const [open, setOpen] = useState(false); const [error, setError] = useState("");
  async function request(method: "PATCH" | "DELETE", data?: object) { setError(""); const response = await fetch(`/api/projects/${project.id}`, { method, headers: { "Content-Type": "application/json" }, body: data ? JSON.stringify(data) : undefined }); const result = await response.json(); if (!response.ok) setError(result.error || "Toiminto epäonnistui."); else { setOpen(false); if (method === "DELETE" || (data as { archived?: boolean })?.archived) router.push("/tyomaat"); else router.refresh(); } }
  return <div className="flex flex-wrap items-center justify-end gap-3"><button onClick={() => setOpen(true)} className="text-sm font-semibold text-[#142b45] underline">Muokkaa tietoja</button><button onClick={() => request("PATCH", { archived: true })} className="text-sm font-semibold text-[#52657c] underline">Arkistoi</button><button onClick={() => { if (confirm("Poistetaanko kohde pysyvästi?")) request("DELETE"); }} className="text-sm font-semibold text-red-700 underline">Poista</button>{error && <p className="basis-full text-right text-xs text-red-700">{error}</p>}{open && <div className="fixed inset-0 z-50 overflow-y-auto bg-[#142b45]/55 p-4"><form onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); const details = Object.fromEntries([...fields.map(([key]) => key), "notes"].map(key => [key, String(form.get(key) || "")])); const customerId = String(form.get("customerId") || ""); request("PATCH", { name: form.get("name"), location: form.get("location"), projectType: form.get("projectType"), ...(customerId ? { customerId } : {}), projectDetails: details }); }} className="mx-auto my-6 w-full max-w-3xl bg-white p-6 text-left shadow-2xl"><h2 className="text-xl font-semibold">Muokkaa työmaan tietoja</h2><p className="mt-1 text-sm text-[#607188]">Työmaa on pääasia. Liitä sille tilaaja ja täydennä vastuuhenkilöt vaiheittain.</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="block text-sm font-medium">Työmaan nimi<input required name="name" defaultValue={project.name} className="mt-2 w-full border p-3" /></label><label className="block text-sm font-medium">Tilaaja <span className="font-normal text-[#607188]">(voit lisätä myöhemmin)</span><select name="customerId" defaultValue={project.customerId ?? ""} className="mt-2 w-full border p-3"><option value="">Ei vielä tilaajaa</option>{customers.map(customer => <option key={customer.id} value={customer.id}>{customer.name}</option>)}</select></label><label className="block text-sm font-medium">Osoite tai paikkakunta<input name="location" defaultValue={project.location ?? ""} className="mt-2 w-full border p-3" /></label><label className="block text-sm font-medium">Kohdeluokka<input name="projectType" defaultValue={project.projectType ?? ""} className="mt-2 w-full border p-3" /></label>{fields.map(([key, label, type]) => <label key={key} className="block text-sm font-medium">{label}<input name={key} type={type} defaultValue={project.details[key] ?? ""} className="mt-2 w-full border p-3" /></label>)}</div><label className="mt-4 block text-sm font-medium">Työmaan lisätiedot ja muistiinpanot<textarea name="notes" defaultValue={project.details.notes ?? ""} rows={4} className="mt-2 w-full border p-3" /></label><div className="mt-5 flex gap-3"><button className="rounded bg-[#d9ae16] px-4 py-2 font-semibold">Tallenna muutokset</button><button type="button" onClick={() => setOpen(false)} className="underline">Peruuta</button></div></form></div>}</div>;
}
