import Link from "next/link";
import { Shell } from "@/components/dashboard/shell";
import { CreateUnifiedRecord } from "@/components/dashboard/create-unified-record";
import { ProjectRowActions } from "@/components/dashboard/project-row-actions";
import { createClient } from "@/lib/supabase/server";

type Project = { id: string; name: string; location: string | null; project_type: string | null; project_details: Record<string, string>; customer: { contact_name: string | null; email: string | null; phone: string | null }[] };

export default async function Customers() {
  const supabase = await createClient();
  const primary = await supabase.from("projects").select("id,name,location,project_type,project_details,customer:customers(contact_name,email,phone)").is("archived_at", null).order("created_at", { ascending: false });
  const fallback = primary.error ? await supabase.from("projects").select("id,name,location,project_type,customer:customers(contact_name,email,phone)").is("archived_at", null).order("created_at", { ascending: false }) : null;
  const projects = (primary.data ?? fallback?.data?.map(project => ({ ...project, project_details: {} })) ?? []) as Project[];
  return <Shell><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-[#a67a00]">Kohderekisteri</p><h1 className="mt-2 text-3xl font-semibold">Asiakkaat ja kohteet</h1><p className="mt-2 max-w-3xl text-sm text-[#607188]">Yksi rivi on yksi asiakas tai kohde. Se sisältää kohteen tiedot, yhteyshenkilöt, tarjoukset, laskut ja valvonnan — ilman päällekkäisiä asiakas- ja työmaatasoja.</p></div><CreateUnifiedRecord /></div><div className="mt-8 overflow-hidden border border-[#d6dee7] bg-white shadow-sm"><div className="grid grid-cols-[1fr_.8fr_auto] gap-4 border-b border-[#d6dee7] bg-[#f4f7fa] px-5 py-3 text-xs font-semibold uppercase tracking-wide text-[#607188]"><span>Asiakas / kohde</span><span>Tiedot</span><span>Toiminnot</span></div>{projects.length ? projects.map(project => { const contact = project.customer[0]; return <div key={project.id} className="grid grid-cols-[1fr_.8fr_auto] items-center gap-4 border-b border-[#e4e9ef] px-5 py-4 text-sm last:border-0"><div><Link href={`/tyomaat/${project.id}`} className="font-semibold text-[#142b45] underline">{project.name}</Link><p className="mt-1 text-xs text-[#607188]">{[project.location, project.project_type].filter(Boolean).join(" · ") || "Täydennä kohteen tiedot"}</p></div><span className="text-[#607188]">{[contact?.contact_name, contact?.email, contact?.phone].filter(Boolean).join(" · ") || "Yhteystiedot voi lisätä kohteen muokkauksessa"}</span><div className="flex flex-wrap items-center justify-end gap-3"><Link href={`/tyomaat/${project.id}`} className="rounded bg-[#112b49] px-3 py-2 text-xs font-semibold text-white">Avaa kohde</Link><ProjectRowActions project={{ id: project.id, name: project.name, location: project.location, projectType: project.project_type, details: project.project_details }} /></div></div>; }) : <p className="p-8 text-sm text-[#607188]">Ei vielä kohteita. Perusta ensimmäinen kohde painikkeella.</p>}</div></Shell>;
}
